version: 2

workflows:
  version: 2
  hello:
    jobs:
      - hello:
          filters:
            branches:
              only: master
      - goodbye:
          requires:
            - hello
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/

jobs:
  hello:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "hello"
  goodbye:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "goodbye"

